spring:
  datasource:
    url: jdbc:mysql://localhost:3306/exam
    username: root
    password: Password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8080
  error:
    include-message: always
    include-exception: true
    include-stacktrace: never